language: go

go:
  - 1.6
  - tip

go_import_path: github.com/jochasinga/rx

install:
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert

script: goveralls -service travis-ci -repotoken $COVERALLS_TOKEN