language: go

go:
  - 1.9
  - '1.10'
  - '1.11'
  - tip

go_import_path: github.com/reactivex/rxgo

install:
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert
  - go get github.com/gorilla/websocket

script: goveralls -service travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  webhooks:
    urls:
      - $GITTER_WEBHOOKS
    on_success: change
    on_failure: always
    on_start: never
